// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pltjqahdsvlngfjyqoma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsdGpxYWhkc3Zsbmdmanlxb21hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NzQxNTIsImV4cCI6MjA1ODU1MDE1Mn0.Z93LG4rwoU9jFg8ZrHPocKMfwxwzXvDi4rnk2S-9pPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);